/**
 * Represents one local project folder managed by AIRI.
 *
 * @param TMetadata Additional runtime metadata stored by a concrete host.
 */
export interface Project<TMetadata extends Record<string, unknown> = Record<string, unknown>> {
  /** Stable project id generated by AIRI. */
  id: string
  /** User-visible project name. Defaults to the registered folder name. */
  name: string
  /** User-provided uppercase issue prefix such as `AIRI`. */
  issuePrefix: string
  /** Absolute local folder path. */
  rootPath: string
  /** Whether the registered folder is inside a git work tree. */
  gitEnabled: boolean
  /** Optional user-provided command used when AIRI cannot infer tests. */
  testCommand?: string
  /** Host-specific metadata that should not affect domain helpers. */
  metadata: TMetadata
  /** Epoch milliseconds when the project was registered. */
  createdAt: number
  /** Epoch milliseconds when the project was last changed. */
  updatedAt: number
}

/**
 * Input used when registering a local project folder.
 */
export interface ProjectRegistrationInput {
  /** Absolute local folder path selected by the user. */
  rootPath: string
  /** User-visible project name. */
  name: string
  /** User-provided uppercase issue prefix such as `AIRI`. */
  issuePrefix: string
  /** Whether AIRI detected git support for the folder. */
  gitEnabled: boolean
}
