export type WorkItemRunStatus = 'queued' | 'in_progress' | 'in_review' | 'done' | 'blocked' | 'cancelled'

/**
 * Records one local worker/reviewer execution attempt for a work item.
 */
export interface WorkItemRunRecord {
  /** Stable run id generated by AIRI. */
  id: string
  /** Work item id this run belongs to. */
  workItemId: string
  /** Current run status. */
  status: WorkItemRunStatus
  /** Current review attempt, starting at 0. */
  attempt: number
  /** File paths changed by the worker. */
  changedFiles: string[]
  /** Local git worktree path used by the worker and reviewer agents. */
  worktreePath?: string
  /** Git branch checked out in the worker worktree. */
  branchName?: string
  /** Short diff summary shown in board details. */
  diffSummary?: string
  /** Short worker comment shown in board details. */
  workerComment?: string
  /** Short reviewer comment shown in board details. */
  reviewerComment?: string
  /** Optional test command AIRI ran. */
  testCommand?: string
  /** Optional test result summary. */
  testSummary?: string
  /** Commit hash when automatic commit succeeds. */
  commitHash?: string
  /** Commit message AIRI generated. */
  commitMessage?: string
  /** Error summary when the run cannot complete. */
  error?: string
  /** Epoch milliseconds when the run started. */
  startedAt: number
  /** Epoch milliseconds when the run finished. */
  finishedAt?: number
}
