export type WorkItemStatus = 'todo' | 'in_progress' | 'in_review' | 'done' | 'blocked' | 'cancelled'

export type WorkItemPriority = 'urgent' | 'high' | 'medium' | 'low' | 'none'

export type WorkItemActorType = 'user' | 'airi' | 'worker' | 'reviewer' | 'system'

/**
 * Represents a user-visible unit of work in a registered local project.
 */
export interface WorkItem {
  /** Stable internal id generated by AIRI. */
  id: string
  /** Project id this item belongs to. */
  projectId: string
  /** User-entered identifier such as `AIRI-12`. */
  identifier: string
  /** Short title shown on cards and in chat summaries. */
  title: string
  /** Goal AIRI confirmed with the user before creating the item. */
  goal: string
  /** Completion criteria AIRI confirmed with the user. */
  acceptanceCriteria: string[]
  /** Optional external tracker prefix prepended to automatic commit messages. */
  commitPrefix?: string
  /** Current execution status. */
  status: WorkItemStatus
  /** User-facing priority. */
  priority: WorkItemPriority
  /** Optional branch/worktree-ready ordering value for future board sorting. */
  position: number
  /** Optional epoch milliseconds due date. */
  dueAt?: number
  /** Epoch milliseconds when the item was created. */
  createdAt: number
  /** Epoch milliseconds when the item was last changed. */
  updatedAt: number
}

/**
 * Input used when AIRI creates a work item from chat or the board.
 */
export interface CreateWorkItemInput {
  /** Project id this item belongs to. */
  projectId: string
  /** User-entered identifier such as `AIRI-12`. */
  identifier: string
  /** Short title shown on cards and in chat summaries. */
  title: string
  /** Goal AIRI confirmed with the user before creating the item. */
  goal: string
  /** Completion criteria AIRI confirmed with the user. */
  acceptanceCriteria: string[]
  /** Optional external tracker prefix prepended to automatic commit messages. */
  commitPrefix?: string
  /** Optional user-facing priority. */
  priority?: WorkItemPriority
  /** Optional epoch milliseconds due date. */
  dueAt?: number
}

/**
 * Mutable fields AIRI can update after a work item is created.
 */
export interface UpdateWorkItemInput {
  /** New title shown on cards and in chat summaries. */
  title?: string
  /** Updated user goal. */
  goal?: string
  /** Updated completion criteria. */
  acceptanceCriteria?: string[]
  /** Updated external tracker prefix; null clears the field. */
  commitPrefix?: string | null
  /** New workflow status. */
  status?: WorkItemStatus
  /** New priority. */
  priority?: WorkItemPriority
  /** New board ordering position. */
  position?: number
  /** New due date; null clears the field. */
  dueAt?: number | null
}

/**
 * Represents a short comment or execution note attached to a work item.
 */
export interface WorkItemComment {
  /** Stable comment id generated by AIRI. */
  id: string
  /** Work item id this comment belongs to. */
  workItemId: string
  /** Actor that produced this comment. */
  actorType: WorkItemActorType
  /** Human-readable comment body. */
  content: string
  /** Optional structured kind used by the board. */
  kind: 'comment' | 'status' | 'worker' | 'review' | 'diff' | 'test' | 'commit'
  /** Epoch milliseconds when the comment was created. */
  createdAt: number
}
